---
title: "DataWrangling"
output: html_document
editor_options: 
  chunk_output_type: console
---

# Load in Packages / Data
```{r}
library(tidyverse)
library(here)
library(lubridate)

seaotter_data <- read.csv(here("Data/GLBA_SEOT_forage_bouts_1993-2019(1).csv"))
```

# Create Year and Month Columns / Filter for Variables of Interest / Rid NAs and unidentified prey items
```{r}
seaotter_data$bout_date <- ymd(seaotter_data$bout_date)

unique(seaotter_data$success_cd)

seaotter_data <- seaotter_data %>%
  mutate(year = year(bout_date)) %>%
  mutate(month = month(bout_date)) %>%
  filter(site_name != "") %>%
  filter(preytype_cd != "uni")%>%
  filter(preytype_cd != "egm") %>%
  filter(sex_cd != "u") %>%
  select("bout_date", "year", "month", "sex_cd", "site_name", "dive_time", "success_cd", "preytype_cd", "prey_qty", "preysize_cd")

unique(seaotter_data$success_cd)

```

# Adding Phylum groups
```{r}
preytype_data <- read.csv(here("Data/GLBA_SEOT_forage_taxonomy_1993-2019(1).csv"))

preytype_data <- preytype_data %>%
  select("preytype_cd", "common_name", "phylum")

seaotter_preytype <- seaotter_data 

annelida_codes <- c("ecs", "wor") 
arthropoda_codes <- c( "bas","cam","can","cao","cap","chb","cra","hes","hyl", "org","pac","pag","pas","pcr","pug","pup","pus","tec")
chordata_codes <- c("feg", "fis", "haa")
echinodermata_codes <- c("apc", "crp", "cuc", "cuf", "cum", "evt", "goc", "gos", "les", "ops", "pis", "pyh", "sos", "sta", "std", "stf", "stp", "urc")
mollusca_codes <- c("biv", "chi", "chl", "cla", "cln", "crg", "crs", "enn", "eul", "fuo", "gac", "huk", "kat", "lim", "lua", "man", "map", "mas", "mom", "msc", "mtr", "mus", "mya", "mys", "myt", "nes", "ocd", "paa", "pat", "pom", "prs", "sag", "sca", "seg", "sip", "sna", "spi", "trc")
porifera_codes <-c("spo")
sipuncula_codes <-c("pha")

#adding to big dataset
seaotter_data$phylum <- ifelse( seaotter_preytype$preytype_cd %in% annelida_codes, "Annelida", 
                            ifelse( seaotter_preytype$preytype_cd %in% arthropoda_codes, "Arthropoda", 
                            ifelse( seaotter_preytype$preytype_cd %in% chordata_codes, "Chordata",
                            ifelse( seaotter_preytype$preytype_cd %in% echinodermata_codes, "Echinodermata",
                            ifelse( seaotter_preytype$preytype_cd %in% mollusca_codes, "Mollusca",
                            ifelse( seaotter_preytype$preytype_cd %in% porifera_codes, "Porifera",    
                            ifelse( seaotter_preytype$preytype_cd %in% sipuncula_codes, "Sipuncula", NA)))))))

```

#Saving cleaned data
```{r}
#writing seaotter_data to cleaned csv
write_csv(seaotter_data, "./Data/cleaned_seaotter_data.csv")
```

# Does the proportion of successful foraging attempts of sea others within Glacier Bay National Park vary with gender?
```{r}
sex_success <- cleaned_seaotter_data %>%
  filter(sex_cd != "u") %>%
  count(sex_cd, success_cd) %>%
  rename(count_success = n)

sex_success_proportion <- sex_success %>%
  pivot_wider(names_from = success_cd, values_from = count_success)

sex_success_proportion <- sex_success_proportion %>% 
  mutate(successful_proportion = y/(y+n))
```


