---
title: "Exploratory Figures"
author: "Alonso Velasquez"
date: "2026-03-18"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

```{r}
library(tidyverse)
library(here)

cleaned_seaotter_data <- read_csv(here("Data/cleaned_seaotter_data.csv"))
```



### Does longer bout time equal more successful forage capture?
```{r}
cleaned_seaotter_data <- cleaned_seaotter_data %>% 
  filter(success_cd == "y" | success_cd == "n") %>% 
  filter(sex_cd != "u")

dive_time_summary <- cleaned_seaotter_data %>%
  group_by(success_cd) %>%
  summarize(
    mean_dive_time = mean(dive_time, na.rm = TRUE),
    sd_dive_time = sd(dive_time, na.rm = TRUE),
    sample_size = n()
  ) %>%
  ungroup()

print(dive_time_summary)

cleaned_seaotter_data %>% 
  ggplot(aes(x= success_cd, y = dive_time, color = success_cd)) +
  geom_jitter(size = 1, alpha = 0.05, stroke = 1) +
  geom_boxplot(alpha= 0.88) +
  theme_minimal() +
  labs(x = "Successful Forage Bout", y = "Dive Time (seconds)", title = "Sea Otter Dive Time and Forage Bout Success", caption = "Unsuccessful forage bouts had an average dive time of 63.0s, while successful forage bouts had an average dive time of 72.3s") +
  theme(legend.position = "none")
```

#Looking at variables
```{r}
#examining dive time by gender
ggplot(cleaned_seaotter_data, aes(x=dive_time)) +
  geom_histogram() +
  labs(x = "Dive Time (seconds)",
       y = "Count") +
  facet_grid(~sex_cd)

#examining bout date
ggplot(cleaned_seaotter_data, aes(x=bout_date)) +
  geom_histogram() +
  labs(x = "Bout Date (year)",
       y = "Count")
```


```{r}
#T-Test!!!

#creating two different datasets
successful_dive_time <- cleaned_seaotter_data %>% 
  filter(success_cd == "y")
unsuccessful_dive_time <- cleaned_seaotter_data %>% 
  filter(success_cd == "n")

successful_dive_ttest <- t.test(x = successful_dive_time$dive_time,
                                     y = unsuccessful_dive_time$dive_time)

successful_dive_ttest
```

#does success change by site name?
```{r}
seaotter_success_site <- cleaned_seaotter_data %>%
  filter(success_cd == "y") %>%
  group_by(site_name) %>%
  count(success_cd) %>%
  rename(count_success = "n")

seaotter_failure_site <- cleaned_seaotter_data %>%
  filter(success_cd == "n") %>%
  group_by(site_name) %>%
  count(success_cd) %>%
  rename(count_failure = "n")

proportion_success_site <- seaotter_success_site %>% 
  left_join(seaotter_failure_site %>%
              select(count_failure), by = "site_name")

proportion_success_site <- proportion_success_site %>% 
  mutate(proportion_success = count_success / (count_success+count_failure))
```

#does success change by sex?
```{r}
sex_success <- cleaned_seaotter_data %>%
  filter(sex_cd != "u") %>%
  count(sex_cd, success_cd) %>%
  rename(count_success = n)

sex_success_proportion <- sex_success %>%
  pivot_wider(names_from = success_cd, values_from = count_success)

sex_success_proportion <- sex_success_proportion %>% 
  mutate(successful_proportion = y/(y+n))
```


