---
title: "SuccessLogisticRegression"
author: "Alonso Velasquez"
date: "2026-04-06"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

```{r}
#Loading packages
library(tidyverse)
library(here)
library(naniar)
library(DHARMa)
library(gtsummary)
library(broom)
library(moments)
#install.packages("car")
library(car)
#install.packages("lme4", type = "source")
library(lme4)
library(gt)
#install.packages("forcats")
library(forcats)
```

```{r}
#Reading in data
cleaned_seaotter_data <- read_csv(here("Data/cleaned_seaotter_data.csv"))
```

```{r}
#Filtering only usable data
cleaned_seaotter_data1 <- cleaned_seaotter_data %>% 
  filter(!is.na(month)) %>% 
  filter(sex_cd == "f" | sex_cd == "m") %>% 
  filter(!is.na(site_name)) %>% 
  filter(!is.na(dive_time)) %>% 
  filter(!is.na(dive_num)) %>% 
  filter(dive_num <= 20) %>% 
  mutate(dive_num_group = case_when(dive_num <= 5 ~ "early",
                                    TRUE ~ "late")) %>% 
  mutate(dive_num_group = factor(dive_num_group, levels = c("early", "late"))) %>% 
  mutate(dive_num_group = factor(dive_num_group, levels = c("early", "mid early", "mid late", "late"))) %>% 
  filter(visibility_cd != "un") %>% 
  filter(ageclass_cd != "u") %>% 
  filter(success_cd == "y" | success_cd == "n") %>% 
  mutate(month = as.factor(month)) %>% 
  mutate(dive_num_factor = as.factor(dive_num)) %>% 
  mutate(ageclass_cd = factor(ageclass_cd, levels = c("j", "s", "a", "o"))) %>% 
  mutate(visibility_cd = factor(visibility_cd, levels = c("po", "fa", "go", "vg", "ex"))) %>% 
  mutate(season = case_when(month == 8 ~ "summer",
                            TRUE ~ "spring")) %>% 
  mutate(visibility_cd = fct_collapse(visibility_cd, po = c("po", "fa"), go = "go",
                                       vg = "vg", ex = "ex")) %>% 
  mutate(success_cd = case_when(success_cd == "y" ~ 1,
                                success_cd == "n" ~ 0))

unique(cleaned_seaotter_data1$dive_num_group)
```

```{r}
#Filtered Data, removing juvenile and old age for age class
cleaned_seaotter_data2 <- cleaned_seaotter_data %>% 
  filter(!is.na(month)) %>% 
  filter(sex_cd == "f" | sex_cd == "m") %>% 
  filter(!is.na(site_name)) %>% 
  filter(!is.na(dive_time)) %>% 
  filter(!is.na(dive_num)) %>% 
  filter(dive_num <= 20) %>%
  mutate(dive_num_group = case_when(dive_num <= 5 ~ "early",
                                    TRUE ~ "late")) %>% 
  mutate(dive_num_group = factor(dive_num_group, levels = c("early", "late"))) %>% 
  filter(visibility_cd != "un") %>% 
  filter(ageclass_cd == "s" | ageclass_cd == "a") %>% 
  filter(success_cd == "y" | success_cd == "n") %>% 
  mutate(month = as.factor(month)) %>% 
  mutate(dive_num_factor = as.factor(dive_num)) %>% 
  mutate(ageclass_cd = factor(ageclass_cd, levels = c("s", "a"))) %>% 
  mutate(visibility_cd = factor(visibility_cd, levels = c("po", "fa", "go", "vg", "ex"))) %>% 
  mutate(season = case_when(month == 8 ~ "summer",
                            TRUE ~ "spring")) %>%
  mutate(visibility_cd = fct_collapse(visibility_cd, po = c("po", "fa"), go = "go",
                                       vg = "vg", ex = "ex")) %>%
  mutate(success_cd = case_when(success_cd == "y" ~ 1,
                                success_cd == "n" ~ 0))

```


```{r}
#Nested Logistic regression 
success_model_BoutID <- glmer(success_cd ~ season + sex_cd + dive_time + dive_num_factor + ageclass_cd + visibility_cd + (1 | site_name) + (1 | bout_id), data = cleaned_seaotter_data1, family = "binomial")

success_model_noBoutID <- glmer(success_cd ~ season + sex_cd + dive_time + dive_num_factor + ageclass_cd + visibility_cd + (1 | site_name), data = cleaned_seaotter_data1, family = "binomial")

success_model_BoutID_noDiveNum <- glmer(success_cd ~ season + sex_cd + dive_time + ageclass_cd + visibility_cd + (1 | site_name) + (1 | bout_id), data = cleaned_seaotter_data1, family = "binomial")

success_model_BoutID_TrimAgeClass <- glmer(success_cd ~ season + sex_cd + dive_time + dive_num_factor + ageclass_cd + visibility_cd + (1 | site_name) + (1 | bout_id), data = cleaned_seaotter_data2, family = "binomial")

success_model_BoutID_TrimAgeClass_NoVisibility <- glmer(success_cd ~ season + sex_cd + dive_time + dive_num_factor + ageclass_cd + (1 | site_name) + (1 | bout_id), data = cleaned_seaotter_data2, family = "binomial")

success_model_DiveGroup <- glmer(success_cd ~ season + sex_cd + dive_time + dive_num_group + ageclass_cd + (1 | site_name) + (1 | bout_id), data = cleaned_seaotter_data2, family = "binomial")

summary(success_model_BoutID)
summary(success_model_noBoutID)
summary(success_model_BoutID_TrimAgeClass)
summary(success_model_BoutID_TrimAgeClass_NoVisibility)

summary(success_model_DiveGroup)

AIC(success_model_BoutID, success_model_noBoutID, success_model_BoutID_TrimAgeClass, success_model_BoutID_TrimAgeClass_NoVisibility)
```

```{r}
# Explore Model With Best AIC
simulateResiduals(success_model_BoutID_TrimAgeClass_NoVisibility) %>%
  plot()

#Looking at infravariable effectzzz
summary(success_model_BoutID_TrimAgeClass_NoVisibility)

```

```{r}
####Dive Time Descriptive Statistics
dive_time_summary <- cleaned_seaotter_data2 %>%
  group_by(success_cd) %>%
  summarize(
    mean_dive_time = mean(dive_time, na.rm = TRUE),
    sd_dive_time = sd(dive_time, na.rm = TRUE),
    sample_size = n()) %>%
  ungroup()

print(dive_time_summary)

dive_time_plot <- cleaned_seaotter_data2 %>% 
  ggplot(aes(x= as.factor(success_cd), y = dive_time, color = as.factor(success_cd))) +
  geom_jitter(size = 1, alpha = 0.05, stroke = 1) +
  geom_boxplot(alpha= 0.88) +
  theme_minimal() +
  scale_x_discrete(labels = c("0" = "Fail", "1" = "Success")) +
  ylim(min = 0, max = 250) +
  labs(x = "Successful Forage Bout", y = "Dive Time (seconds)", title = "Sea Otter Dive Time and Foraging Bout Dive Success") +
  theme(legend.position = "none", text = element_text(family = "Times New Roman"), plot.title = element_text(face = "bold", size = 14)) 

ggsave("divetime_plot.png", plot = dive_time_plot, dpi = 500)

"Unsuccessful forage bouts had an average dive time of 58.6s (sd = 35.0, n = 313), while successful forage bouts had an average dive time of 70.9s (sd = 34.4, n = 5096).  \nThere is a statistically significant difference in means between unsuccessful and succesful \nforage bouts according to a two-tailed two-sample t-test (t = 7.85, df = 1376.1, p = 8.011e-15)"

#creating two different datasets
successful_dive_time <- cleaned_seaotter_data2 %>% 
  filter(success_cd == "1")
unsuccessful_dive_time <- cleaned_seaotter_data2 %>% 
  filter(success_cd == "0")

t.test(x = successful_dive_time$dive_time, y = unsuccessful_dive_time$dive_time,alternative = "greater")

```

```{r}
#Creating count table for categorical variables
cleaned_seaotter_data2 %>%
  mutate(ageclass_cd = fct_recode(ageclass_cd, "subadult" = "s", 
                                  "adult" = "a"), 
         sex_cd = fct_recode(sex_cd, "female" = "f", "male" = "m"),
         dive_num_group = fct_recode(dive_num_group, "early (<= 5)" = "early", "late (>5)" = "late")) %>%
  select(success_cd, ageclass_cd, sex_cd, season, dive_num_group) %>%
  tbl_summary(by = success_cd, label = list(ageclass_cd ~ "Age Class",
      sex_cd ~ "Sex", season ~ "Season", dive_num_group ~ "Dive Number (Early vs. Late)"), digits = all_categorical() ~ c(0, 0)) %>%
  modify_header(label ~ "Variable", stat_1 ~ "Fail (O)", stat_2 ~ "Success (1)") %>%
modify_footnote(all_stat_cols() ~ "Count (Percent); Fail n = 313, Success n = 5,096") %>% 
  as_gt() %>% 
  fmt_number(columns = c(stat_1, stat_2), decimals = 0) %>% 
  tab_options(table.font.names = "Times New Roman", table.width = pct(100))
  
```


```{r}
#Checking for multicolinearity


#Categorical variables success and sex correlation?
success_sex_data <- table(cleaned_seaotter_data1$success_cd,
                    cleaned_seaotter_data1$sex_cd)

chisq.test(success_sex_data)
#X-squared = 3.9197e-30, df = 1, p-value = 1 --no correlation 


#Dive number & Dive time correlation?
cor.test(
  as.numeric(as.character(cleaned_seaotter_data2$dive_num)),
  cleaned_seaotter_data2$dive_time)
#t = -4.6847, df = 5544, p-value = 2.871e-06



```

```{r}
### MAKING TABLES ###

model_summary <- summary(success_model_BoutID_TrimAgeClass_NoVisibility)

model_df <- as.data.frame(model_summary$coefficients) %>%
  mutate(term = rownames(model_summary$coefficients)) %>%
  select(term, Estimate, `Std. Error`, `z value`, `Pr(>|z|)`)

dive_num_table <- model_df %>%
  filter(str_detect(term, "dive_num_factor"))

other_terms_table <- model_df %>%
  filter(!str_detect(term, "dive_num_factor")) %>% 
  mutate(term = case_when(
    term == "seasonsummer" ~ "season (summer)",
    term == "sex_cdm" ~ "sex (male)",
    term == "dive_time" ~ "dive time, seconds",
    term == "ageclass_cda" ~ "age class (adult)",
    TRUE ~ term))


dive_num_table %>%
  gt() %>%
  cols_label(term = "Term") %>%
  fmt_number(columns = c(Estimate, `Std. Error`, `z value`, `Pr(>|z|)`), decimals = 3) %>%
  tab_header(title = "Dive Success Mixed-Effects Logistic Regression: Dive Number (Fixed Effect)") %>% 
  tab_options(table.font.names = "Times New Roman", table.width = pct(100))

other_terms_table %>%
  gt() %>%
  cols_label(term = "Term") %>%
  fmt_number(columns = c(Estimate, `Std. Error`, `z value`, `Pr(>|z|)`), decimals = 3) %>%
  tab_header(title = "Dive Success Mixed-Effects Logistic Regression: Fixed Effects (excluding Dive Number)") %>% 
  tab_options(table.font.names = "Times New Roman", table.width = pct(100))
  
```

```{r}
### AIC Table
model_AICs <- AIC(success_model_BoutID, success_model_noBoutID, success_model_BoutID_TrimAgeClass, success_model_BoutID_TrimAgeClass_NoVisibility)

AIC_df <- as.data.frame(model_AICs) %>% 
  mutate(Model = rownames(model_AICs)) %>%
  select(Model, df, AIC) %>% 
  mutate(Model = case_when(
    Model == "success_model_BoutID" ~ "Bout ID",
    Model == "success_model_noBoutID" ~ "No Bout ID",
    Model == "success_model_BoutID_TrimAgeClass" ~ "Bout ID, Trimmed Age Class",
    Model == "success_model_BoutID_TrimAgeClass_NoVisibility" ~ "Bout ID, Trimmed Age Class, No Visibility",
    TRUE ~ Model)) 

AIC_df %>%
  gt() %>% 
  tab_options(table.font.names = "Times New Roman", table.width = pct(100))

```

```{r}
#Random effects table
re_df <- as.data.frame(VarCorr(success_model_BoutID_TrimAgeClass_NoVisibility)) %>% 
  select(-var2) %>% 
  mutate(grp = case_when(
    grp == "bout_id" ~ "bout ID",
    grp == "site_name" ~ "site name",
    TRUE ~ grp))

re_df %>%
  gt() %>%
  cols_label(grp = "Group", var1 = "Type", vcov = "Variance",
             sdcor = "Std. Dev.") %>%
  tab_header(title = "Dive Success Mixed-Effects Logistic Regression: Random Effects") %>% 
  fmt_number(columns = c(vcov, sdcor), decimals = 4) %>%
  tab_options(table.font.names = "Times New Roman", table.width = pct(100))
```

